[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=0
    -DPIN_SCK=36
    -DPIN_MISO=37
    -DPIN_MOSI=35
    -DPIN_CS=34
    -DPIN_GDO0=33
    -DPIN_GDO2=16
    -DPIN_LED=15
    -DPIN_BOOT=0
    -DPRESENCE_TIMEOUT_MS=30000
board_upload.use_1200bps_touch = true
board_upload.wait_for_upload_port = true
lib_deps =
    jgromes/RadioLib@^7.1.2
    bblanchon/ArduinoJson@^7.0.0
monitor_speed = 115200
monitor_dtr = 1